en:
  features:
  - title: Namespace strategies
    summary: >
      The grouping of repositories can be changed by the applied namespace strategy.
      You can choose between type of repository, username of creator, year of creation and custom.
      Custom allows you to set a namespace for each repository.
    link: https://scm-manager.org
  - title: Permission
    summary: >
      Permissions for users and groups can be set globally, individually for each repository or in a combination of both.
      Global permissions can be set in the administration area and the individual permissions in the repository settings.
      Choose the method that suites your needs. 
    link: https://scm-manager.org
  - title: Create branches
    summary: >
      New braches can be created directly in SCM-Manager.
      Just go to the banches page of the repository navigation.
    link: https://scm-manager.org
  - title: Repository permissions
    summary: >
      It is possible to create individual roles for repository permissions.
      You can choose between all availble actions in SCM-Manager to create exactly the roles that you need.
    link: https://scm-manager.org

  plugins:
  - title: LDAP
    summary: >
      You do not have to use local SCM-Manager users only. The LDAP plugin allows you to connect SCM-Manager
      to a directory service.
    link: https://plugins.scm-manager.org/scm-plugin-backend/page/index.html
  - title: Support
    summary: >
      The support plugin gathers log files and system information for you to make troubleshooting easier.
      Once installed, it can easily be activated to gather information.
    link: https://plugins.scm-manager.org/scm-plugin-backend/page/index.html
  - title: Script
    summary: >
      The script plugin 2.0 now not only allows you to execute your scripts manually.
      It also allows you to use hooks to execute scripts automatically.
    link: https://plugins.scm-manager.org/scm-plugin-backend/page/index.html
  - title: SSH
    summary: >
      The SSH plugin allows you to not only access your repositories via http, but also via ssh.
      This allows you to use tokens as well as login credentials to access SCM-Manager.
    link: https://plugins.scm-manager.org/scm-plugin-backend/page/index.html

de:
  features:
  - title: Namespace Strategien
    summary: >
      Durch Namespaces kann die Sortierung der Repositories in der Übersicht beeinflusst werden.
      Es kann zwischen Repository Typ, Usernamen des Erstellers, Erstellungsjahr und benutzerdefiniert gewählt werden.
      Bei Benutzerdefiniert kann für jedes Repository individuell der Namespace eingestellt werden.
    link: https://scm-manager.org
  - title: Berechtigungen
    summary: >
      Berechtigungen können global, je Repository oder als Kombination der beiden Wege vergeben werden.
      Globale Berechtigungen werden im Administrationsbereich eingetragen. Repository-Berechtigungen in den Einstellungen der Repositories.
    link: https://scm-manager.org
  - title: Branches erstellen
    summary: >
      Neue Branches können direkt in SCM-Manager 2 auf der Branch Übersichtsseite erstellt werden.
    link: https://scm-manager.org
  - title: Repository Berechtigungen
    summary: >
      In SCM-Manager 2 können individuelle Rollen erstellt werden.
      Dafür stehen alle Aktionen aus SCM-Manager zur Auswahl um die exakt passenden Rollen zu erstellen.
    link: https://scm-manager.org

  plugins:
  - title: LDAP
    summary: >
      Man muss nicht nur lokale SCM-Manager Nutzer benutzen. Das LDAP Plugin ermöglicht es SCM-Manager an einen Verzeichnisdienst anzubinden.
    link: https://plugins.scm-manager.org/scm-plugin-backend/page/index.html
  - title: Support
    summary: >
      Das Support Plugin sammelt Log-Dateien und Systeminformationen um die Fehlersuche zu vereinfachen.
      Sobald es installiert ist kann es ganz einfach aktiviert werden um die Informationen aufzuzeichnen.
    link: https://plugins.scm-manager.org/scm-plugin-backend/page/index.html
  - title: Script
    summary: >
      Das Script Plugin 2.0 ermöglicht es nicht nur Skripte manuell auszuführen.
      Es bietet nun auch die Möglichkeit die Ausführung von Skripten durch Hooks zu automatisieren.
    link: https://plugins.scm-manager.org/scm-plugin-backend/page/index.html
  - title: SSH
    summary: >
      Das SSH Plugin erlaubt es Repositories nicht nur über http, sondern auch über ssh aufzurufen.
      Dadurch können sie nicht nur mit Login Daten, sondern auch mit Tokens aufgerufen werden.
    link: https://plugins.scm-manager.org/scm-plugin-backend/page/index.html

