apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  {{- $files := .Files }}
  {{- range list "config.yaml" }}
  {{ . }}: |-
{{ $files.Get . | indent 4 }}
  {{- end }}
